//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


@class MessageData, NSMutableDictionary;

@protocol MMRevokeMsgServiceExt <NSObject>

@optional
- (void)messageCellViewReloadLayout:(MessageData *)arg1;
- (void)messageCellViewRevoking:(MessageData *)arg1;
- (void)messageWillBeRevoked:(MessageData *)arg1 revokeContext:(NSMutableDictionary *)arg2;
@end

