//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface MMTextField : NSTextField
{
    long long _vibrancyMode;
    unsigned long long _style;
    CDUnknownBlockType _menuForEventBlock;
    CDUnknownBlockType _didBecomeFirstResponderBlock;
    CDUnknownBlockType _didResignFirstResponderBlock;
}

- (void).cxx_destruct;
- (BOOL)allowsVibrancy;
- (BOOL)becomeFirstResponder;
@property(copy, nonatomic) CDUnknownBlockType didBecomeFirstResponderBlock; // @synthesize didBecomeFirstResponderBlock=_didBecomeFirstResponderBlock;
@property(copy, nonatomic) CDUnknownBlockType didResignFirstResponderBlock; // @synthesize didResignFirstResponderBlock=_didResignFirstResponderBlock;
- (id)initWithFrame:(struct CGRect)arg1;
@property(copy, nonatomic) CDUnknownBlockType menuForEventBlock; // @synthesize menuForEventBlock=_menuForEventBlock;
- (BOOL)performKeyEquivalent:(id)arg1;
- (BOOL)resignFirstResponder;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) long long vibrancyMode; // @synthesize vibrancyMode=_vibrancyMode;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;

@end

